name: demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_native_splash: ^2.2.12
  flutter: 
    sdk: flutter
  json_annotation: ^4.7.0
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^5.4.0
  get_storage: ^2.0.3
  yaml: ^3.1.1

dev_dependencies: 
  build_runner: ^2.3.2
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.5.4

flutter: 
  uses-material-design: true
  assets:
    - assets/images/gopher.png
    - env.local.yaml
    - env.test.yaml
    - env.production.yaml

